### ISSUE TITLE
How to implement onSuccess and onFailure with Data provided by slack? 

### ISSUE THREAD

**Issue by mick-zelta** [hectorbenitez/react-slack-login#1]
Having spent days trying to get the Slack Sign In working for my web app, I'm finding the whole thing tirelessly complex and confusing. Their documentation isn't the best imo. Whenever I use this react-slack-login I get prompted to allow Slack to access my info and authenticate myself (which is a perfect scenario), but then I just get sent to the Redirect URL. How do we intercept the JSON files whenever this transaction takes place (allow slack to access info) and authenticate the user based on my own database credentials?  I need to tie the user to my own database in Firebase to ensure he/she already exists and then if not to register them.

From the description : "The component will return a slack OAuth verifier code, you should send that code to your API and exchange your temporary OAuth verifier code for an access token." But do we need to engage the Slack Web API for this ? Anytime I try to import the slack web api to my typescript project it states that "process is not defined" due tot he javascript files called whenever we call upon the elements imported from the WebAPI (path.js etc.)

Any help is greatly appreciated.

**Comment by hectorbenitez** [comment]
Working on full example

**Comment by hectorbenitez** [comment]
@mick-zelta example added, let us know if works for you

**Comment by mick-zelta** [comment]
Got it working 😄  Did it as a standalone app, will try and integrate with my webapp now - thanks!
